name: Jest Tests
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - run: npm install jest
    - run: npm install
    # - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
